CapstoneProject_Ecommerce/Controllers/DETTAGLIOController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CapstoneProject_Ecommerce.Models;

namespace CapstoneProject_Ecommerce.Controllers
{
        [Authorize]
    public class DETTAGLIOController : Controller
    {
        private ModelDBcontext db = new ModelDBcontext();

        // GET: DETTAGLIO
        public ActionResult Index(int id, int quantity, string taglia)
        {
            USER utente = db.USER.Where(x => x.Username == User.Identity.Name).FirstOrDefault();
            if (id > 0)
            {
                TAGLIE t = db.TAGLIE.Where(x => x.IdProdotto == id && x.TagliaProdotto == taglia ).FirstOrDefault();
               
                t.QuantitaTaglia -= quantity;

                if (t.QuantitaTaglia < 0)
                {
                    t.QuantitaTaglia += quantity;
                    ViewBag.Message= $"Quantità non disponibile, rimaste in stock {t.QuantitaTaglia}";
                    return RedirectToAction("Index", "PRODOTTO");
                }
                else
                {
                db.Entry(t).State = EntityState.Modified;
                db.SaveChanges();                   
                }

                DETTAGLIO d = new DETTAGLIO();
                d.IdProdotto = id;
                d.IdTaglia = t.IdTaglie;
                d.Quantita = quantity;
                
                PRODOTTO p = db.PRODOTTO.Find(id);
                d.PrezzoTotale = p.Prezzo * d.Quantita;

                d.IdUser = utente.IdUser;


                db.DETTAGLIO.Add(d);
                db.SaveChanges();
            }

            return View(db.DETTAGLIO.Where(x => x.IdOrdine == null && x.IdUser == utente.IdUser).ToList());
        }


        public ActionResult Carrello()
        {
            USER utente = db.USER.Where(x => x.Username == User.Identity.Name).FirstOrDefault();
            List<DETTAGLIO> dtg = db.DETTAGLIO.Include(x => x.PRODOTTO).Where(d => d.IdOrdine == null && d.IdUser == utente.IdUser).ToList();
            return View(dtg);
        }


        // GET: DETTAGLIO/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DETTAGLIO dETTAGLIO = db.DETTAGLIO.Find(id);
            if (dETTAGLIO == null)
            {
                return HttpNotFound();
            }
            return View(dETTAGLIO);
        }

        // GET: DETTAGLIO/Create
        public ActionResult Create()
        {
            ViewBag.IdOrdine = new SelectList(db.ORDINE, "IdOrdine", "Confermato");
            ViewBag.IdProdotto = new SelectList(db.PRODOTTO, "IdProdotto", "NomeProdotto");
            ViewBag.IdTaglia = new SelectList(db.TAGLIE, "IdTaglie", "TagliaProdotto");
            ViewBag.IdUser = new SelectList(db.USER, "IdUser", "Username");
            return View();
        }

        // POST: DETTAGLIO/Create
        // Per la protezione da attacchi di overposting, abilitare le proprietà a cui eseguire il binding. 
        // Per altri dettagli, vedere https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IdDettaglio,IdUser,IdTaglia,IdOrdine,IdProdotto,Quantita,PrezzoTotale")] DETTAGLIO dETTAGLIO)
        {
            if (ModelState.IsValid)
            {
                db.DETTAGLIO.Add(dETTAGLIO);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.IdOrdine = new SelectList(db.ORDINE, "IdOrdine", "Confermato", dETTAGLIO.IdOrdine);
            ViewBag.IdProdotto = new SelectList(db.PRODOTTO, "IdProdotto", "NomeProdotto", dETTAGLIO.IdProdotto);
            ViewBag.IdTaglia = new SelectList(db.TAGLIE, "IdTaglie", "TagliaProdotto", dETTAGLIO.IdTaglia);
            ViewBag.IdUser = new SelectList(db.USER, "IdUser", "Username", dETTAGLIO.IdUser);
            return View(dETTAGLIO);
        }

        // GET: DETTAGLIO/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DETTAGLIO d = db.DETTAGLIO.Find(id);
            List<SelectListItem> ListaTaglie = new List<SelectListItem>();
            SelectListItem item1 = new SelectListItem { Text = "S", Value = "1" };
            SelectListItem item2 = new SelectListItem { Text = "M", Value = "2" };
            SelectListItem item3 = new SelectListItem { Text = "L", Value = "3" };
            ListaTaglie.Add(item1);
            ListaTaglie.Add(item2);
            ListaTaglie.Add(item3);
            ViewBag.lista = ListaTaglie;

            return View(d);
                   
        }

        // POST: DETTAGLIO/Edit/5
        // Per la protezione da attacchi di overposting, abilitare le proprietà a cui eseguire il binding. 
        // Per altri dettagli, vedere https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(DETTAGLIO d)
        {
            if (ModelState.IsValid)
            {
                
                DETTAGLIO dettaglio = db.DETTAGLIO.Find(d.IdDettaglio);

                var a = "";

                if (d.IdTaglia == 1)
                {
                    a = "S";
                }
                else if (d.IdTaglia == 2)
                {
                    a = "M";
                }
                else if (d.IdTaglia == 3)
                {
                    a = "L";
                }
                if (d.IdTaglia == dettaglio.IdTaglia) 
                {
                    TAGLIE t = db.TAGLIE.Where(x => x.IdProdotto == d.IdProdotto && x.IdTaglie == dettaglio.IdTaglia).FirstOrDefault();
                    t.QuantitaTaglia += dettaglio.Quantita;
                    db.Entry(t).State = EntityState.Modified;
                    db.SaveChanges();
                    dettaglio.IdTaglia = d.IdTaglia;
                }
               
                dettaglio.Quantita = d.Quantita;
                TAGLIE t1 = db.TAGLIE.Where(x => x.IdProdotto == d.IdProdotto && x.IdTaglie == d.IdTaglia).FirstOrDefault();
                t1.QuantitaTaglia -= d.Quantita;
                db.Entry(t1).State = EntityState.Modified;
                db.SaveChanges();
                dettaglio.PrezzoTotale = dettaglio.PRODOTTO.Prezzo * d.Quantita;
                               
                db.Entry(dettaglio).State = EntityState.Modified;
                db.SaveChanges();
            }
            return RedirectToAction("Carrello");
        }

        // GET: DETTAGLIO/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DETTAGLIO dETTAGLIO = db.DETTAGLIO.Find(id);
            if (dETTAGLIO == null)
            {
                return HttpNotFound();
            }
            return View(dETTAGLIO);
        }

        // POST: DETTAGLIO/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            DETTAGLIO dETTAGLIO = db.DETTAGLIO.Find(id);
            db.DETTAGLIO.Remove(dETTAGLIO);
            db.SaveChanges();
            return RedirectToAction("Carrello");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CapstoneProject_Ecommerce/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet">
    <script src="https://kit.fontawesome.com/228474511d.js" crossorigin="anonymous"></script>
    <title>@ViewBag.Title - Applicazione ASP.NET</title>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="d-flex flex-column justify-content-between">
        <div class="d-flex flex-column main ">
            @if (ViewContext.RouteData.Values["Controller"].ToString() == "PRODOTTO")
            {
                <img src="~/Content/Img/SHOP(4).jpg" />

            }
            <nav class="navbar navbar-expand-lg bg-body-tertiary">
                <div class="container-fluid d-flex flex-row">
                    <a class="navbar-brand" href="@Url.Action("Index", "PRODOTTO")">

                        <img src="~/Content/Img/logo.png" id="MyImg" alt="Logo" width="60" class="d-inline-block align-text-top" />
                    </a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>

                    <div class="collapse navbar-collapse text-center justify-content-end" id="navbarNav">

                        <ul class="navbar-nav">
                            @if (User.Identity.IsAuthenticated)
                            {
                                <li class="nav-item">@Html.ActionLink("🔓", "LogOut", "Home")  </li>
                            }
                            else
                            {
                                <li class="nav-item">@Html.ActionLink("🔒", "Login", "Home") </li>
                            }

                            @if (User.Identity.Name == "Admin")
                            {

                                <li class="nav-item">@Html.ActionLink("AREA PRIVATA", "ListaAdmin", "PRODOTTO", null, new { @class = "white-text" })</li>

                            }
                            <li class="nav-item">@Html.ActionLink("HOME", "Index", "PRODOTTO", null, new { @class = "white-text" })</li>

                            @if (User.Identity.Name == "Admin")
                            {

                                <li class="nav-item">@Html.ActionLink("ORDINI", "Index", "Ordine", null, new { @class = "white-text" })</li>
                            }
                            else
                            {
                                <li class="nav-item">@Html.ActionLink("ORDINI", "OrdineConfermato", "Ordine", null, new { @class = "white-text" })</li>

                            }

                            <li class="nav-item">@Html.ActionLink("GUIDA ALLE TAGLIE", "GuidaAlleTaglie", "PRODOTTO", null, new { @class = "white-text" })</li>

                            @if (User.Identity.Name != "Admin")
                            {
                                <li class="nav-item">@Html.ActionLink("🛒", "Carrello", "DETTAGLIO")</li>
                            }
                        </ul>

                    </div>
                </div>
            </nav>
        </div>


        <div>
            @RenderBody()
        </div>

        <div style="background: #11171f;">
            <div >
                <img src="~/Content/Img/bunner down.jpg" style="width:100%;" />
            </div>
            @if (User.Identity.IsAuthenticated)
            {
                <div class="footer-bg ">
                    <div class="row footer-menu">


                        <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
                            <h4 class="text-white">Support</h4>
                            <ul>
                                @*<li><a href="https://www.roces.com/en/terms-and-conditions-of-sale#DELIVERY ">Shipping/Returns</a></li>
                            <li><a href="https://www.roces.com/en/manuals">Manuals</a></li>
                            <li><a href="https://www.roces.com/en/terms-and-conditions-of-sale#GUARANTEE">Warranty</a></li>
                            <li><a href="https://www.roces.com/en/original-product-program">Original Product Program</a></li>
                            <li><a href="https://www.roces.com/en/ec-declarationofconformity">Declaration of Conformity</a></li>
                            <li><a href="https://www.roces.com/en/roces-spare-parts-request">Spare Part Request</a></li>*@
                                <li class="nav-item">@Html.ActionLink("Contacts", "Contatti", "HOME")</li>

                            </ul>
                        </div>
                        <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
                            <h4 class="text-white">Company</h4>
                            <ul>
                                <li class="nav-item">@Html.ActionLink("About me", "ABoutMe", "Home")</li>


                            </ul>
                        </div>
                        <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
                            <ul class="inline-list social-media-icons">
                                <li><a href="https://www.facebook.com/NicolaLerra?ref=hl" target="_blank" rel="nofollow noopener"><i class="fa fa-facebook-square"></i></a></li>
                                <li><a href="https://www.youtube.com/redirect?event=channel_banner&redir_token=QUFFLUhqazl6cUUzME5Lc1dYUG1RQkF5Q1dpSElsRlQ4UXxBQ3Jtc0tsOHBITTBGRDdmWTJuY2pMdHBVRjB3SXpwS1BkOFlBUjI3NHEzektzM0RoX280VGlRZmtDNkZzY0JjdVdqV25XdVdWMWhndGxCZC0wZWIzTlQxRkZDcVViV1Z4cFNCOEhRdjdGYURtb1Y0bGdJQ3F0aw&q=https%3A%2F%2Fwww.instagram.com%2Fnicolalerra%2F" target="_blank" rel="nofollow noopener"><i class="fa fa-instagram"></i></a></li>
                                <li><a href="https://www.youtube.com/channel/UC228kKz_ooJRj-dBTkXCk3w" target="_blank" rel="nofollow noopener"><i class="fa fa-youtube-square"></i></a></li>
                                @*<li><a href="https://twitter.com/Roces_official" target="_blank" rel="nofollow noopener"><i class="fa fa-twitter-square"></i></a></li>
                            <li><a href="https://it.pinterest.com/rocesofficial/" target="_blank" rel="nofollow noopener"><i class="fa fa-pinterest"></i></a></li>*@
                                <li><a href="https://www.linkedin.com/in/nicola-lerra/" target="_blank" rel="nofollow noopener"><i class="fa fa-linkedin-square"></i></a></li>
                            </ul>
                        </div>
                    </div>
                </div>

                <footer class="fto">
                    <p>&copy; @DateTime.Now.Year - Applicazione ASP.NET made with ❤️ by Nicola Lerra</p>
                </footer>
            }
        </div>
    </div>
    @RenderSection("scripts", required: false)
</body>
</html>