CapstoneProject_Ecommerce/Controllers/HomeController.cs
using CapstoneProject_Ecommerce.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;
using System.Web.Security;

namespace CapstoneProject_Ecommerce.Controllers
{
    public class HomeController : Controller
    {
        private ModelDBcontext db = new ModelDBcontext();
        // GET: Home
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Login(USER u)
        {
            if (USER.Autenticato(u.Username, u.Pass))
            {
                FormsAuthentication.SetAuthCookie(u.Username, false);
                return Redirect(FormsAuthentication.DefaultUrl);
            }
            return Redirect("/Home/Login");
        }

        public ActionResult LogOut()
        {
            FormsAuthentication.SignOut();
            return Redirect(FormsAuthentication.DefaultUrl);
        }

        public ActionResult Register()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]

        public ActionResult Register([Bind(Include ="Username,Nome,Cognome,Email,Pass")] USER u) 
        {
                u.Ruolo = "Utente";
            if (db.USER.Where(x => x.Username == u.Username).Count() == 0)
            {
                db.USER.Add(u);
                db.SaveChanges();
                return RedirectToAction("Login", "Home");
            }
            return RedirectToAction("Register", "Home");
        }

        public ActionResult Contatti()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Contatti(Email email)
        {
            
            MailAddress from = new MailAddress(email.mittenteEmail);
            MailAddress to = new MailAddress("nicolalerra@gmail.com");
            MailMessage message = new MailMessage(from, to);
                
            message.Subject = email.Oggetto;
            message.Body = email.Messaggio;
            message.ReplyToList.Add(new MailAddress(email.mittenteEmail));

           
            MailAddress copy = new MailAddress("nicolalerra@hotmail.it");
            message.CC.Add(copy);
            SmtpClient smtp = new SmtpClient();

            smtp.Host = "smtp.gmail.com";
            smtp.Port = 587;
            smtp.EnableSsl = true;
            NetworkCredential nc = new NetworkCredential("nicolalerra@gmail.com", "gmiufcbbchqhnauf");
            smtp.Credentials = nc;
            
                try
                {
                    smtp.Send(message);
                }
                catch (Exception ex)
                {               
                        ex.ToString();
                }
            return View("EmailDone");
        }

        public ActionResult EmailDone()
        {
            return View();
        }

        public ActionResult ABoutMe () 
        {
            return View();
        }
    }
}
    

   

CapstoneProject_Ecommerce/Controllers/PRODOTTOController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;
using CapstoneProject_Ecommerce.Models;
using Microsoft.Ajax.Utilities;
using Newtonsoft.Json.Linq;
using static System.Net.Mime.MediaTypeNames;

namespace CapstoneProject_Ecommerce.Controllers
    
{
    [Authorize(Roles = "Amministratore")]
    public class PRODOTTOController : Controller
    {
        private ModelDBcontext db = new ModelDBcontext();

        // GET: PRODOTTO
        [AllowAnonymous]
        public ActionResult Index()
        {
            List<SelectListItem> idTaglia = new List<SelectListItem>();
            SelectListItem item1 = new SelectListItem { Text = "S", Value = "1" };
            SelectListItem item2 = new SelectListItem { Text = "M", Value = "2" };
            SelectListItem item3 = new SelectListItem { Text = "L", Value = "3" };
            idTaglia.Add(item1);
            idTaglia.Add(item2);
            idTaglia.Add(item3);
            ViewBag.IdTaglia = idTaglia;
            return View(db.PRODOTTO.ToList());
        }

        public JsonResult Check(string quantity, string id, string taglia)
        {
            var idP = Convert.ToInt32(id);
            var quantityP = Convert.ToInt32(quantity);
            TAGLIE t = db.TAGLIE.Where(x => x.IdProdotto == idP && x.TagliaProdotto == taglia).FirstOrDefault();

            t.QuantitaTaglia -= quantityP;

            
            return Json(t, JsonRequestBehavior.AllowGet);
        }

        public ActionResult ListaAdmin()
        {
            return View(db.PRODOTTO.ToList());
        }
        [AllowAnonymous]
        public ActionResult GuidaAlleTaglie()
        {
            return View();
        }

        // GET: PRODOTTO/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PRODOTTO pRODOTTO = db.PRODOTTO.Find(id);
            if (pRODOTTO == null)
            {
                return HttpNotFound();
            }
            return View(pRODOTTO);
        }

        // GET: PRODOTTO/Create
        public ActionResult Create()
        {
            
            return View();
        }

        // POST: PRODOTTO/Create
        // Per la protezione da attacchi di overposting, abilitare le proprietà a cui eseguire il binding. 
        // Per altri dettagli, vedere https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(PRODOTTO pRODOTTO, HttpPostedFileBase File, int Quantità, int QuantitàM, int QuantitàL)
        {
            if (ModelState.IsValid)
            {
                File.SaveAs(Server.MapPath("/Content/Img/" + File.FileName));
                pRODOTTO.Foto = File.FileName;
                db.PRODOTTO.Add(pRODOTTO);
                db.SaveChanges();
                TAGLIE t = new TAGLIE();
                t.IdProdotto = pRODOTTO.IdProdotto;
                t.TagliaProdotto = "S";
                t.QuantitaTaglia = Quantità;
                db.TAGLIE.Add(t);
                db.SaveChanges();
                TAGLIE M = new TAGLIE();
                M.IdProdotto = pRODOTTO.IdProdotto;
                M.TagliaProdotto = "M";
                M.QuantitaTaglia = QuantitàM;
                db.TAGLIE.Add(M);
                db.SaveChanges();
                TAGLIE L = new TAGLIE();
                L.IdProdotto = pRODOTTO.IdProdotto;
                L.TagliaProdotto = "L";
                L.QuantitaTaglia = QuantitàL;
                db.TAGLIE.Add(L);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(pRODOTTO);
        }

        // GET: PRODOTTO/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PRODOTTO pRODOTTO = db.PRODOTTO.Find(id);
            if (pRODOTTO == null)
            {
                return HttpNotFound();
            }
            return View(pRODOTTO);
        }

        // POST: PRODOTTO/Edit/5
        // Per la protezione da attacchi di overposting, abilitare le proprietà a cui eseguire il binding. 
        // Per altri dettagli, vedere https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(PRODOTTO pRODOTTO, HttpPostedFileBase File)
        {
            if (File != null)
            {
                string Path = Server.MapPath("/Content/img/" + File.FileName);
                File.SaveAs(Path);
                pRODOTTO.Foto = File.FileName;
            }
            else
            {
                PRODOTTO p = db.PRODOTTO.Find(pRODOTTO.IdProdotto);
                pRODOTTO.Foto = p.Foto;
            }
            ModelDBcontext db1 = new ModelDBcontext();
            db1.Entry(pRODOTTO).State = EntityState.Modified;
            db1.SaveChanges();

            return RedirectToAction("ListaAdmin");
        }

        // GET: PRODOTTO/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PRODOTTO pRODOTTO = db.PRODOTTO.Find(id);
            if (pRODOTTO == null)
            {
                return HttpNotFound();
            }
            return View(pRODOTTO);
        }

        // POST: PRODOTTO/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)

        {
            List<DETTAGLIO> d = db.DETTAGLIO.Where(x => x.IdProdotto == id).ToList();

            foreach (var item in d)
            {
                db.DETTAGLIO.Remove(item);
                db.SaveChanges();
            }

            PRODOTTO pRODOTTO = db.PRODOTTO.Find(id);
            db.PRODOTTO.Remove(pRODOTTO);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CapstoneProject_Ecommerce/Views/Home/ABoutMe.cshtml
@model CapstoneProject_Ecommerce.Models.USER

@{
    ViewBag.Title = "ABoutMe";
}

<div class="d-flex justify-content-center mb-5">
    <div style=" margin-top: 30px; box-shadow: 2px 4px 6px -5px black; border-radius: 0px 0px 17px 0px; max-width:900px; padding:10px; ">
        <div class="row">
            <div class="col-6">
                <div class="container float-end mt-5" style="margin-right: 30px;">
                    <img src="~/Content/Img/PhotoRoom_20221202_215530.jpg" style="width:200px; float:right;" />
                </div>
            </div>

            <div class="col-6 mt-5">
                <h1 style="margin-left: 10px;">Nicola Lerra</h1>
                <p style="margin-left: 10px;"> Junior Full-Stack Developer</p>

                <div>
                    <h5 style="margin-left: 10px;">Technologies</h5>
                </div>

                <div class="d-flex flex-wrap justify-content-center ">
                    <img src="~/Content/Img/11.png" style="width: 30px; margin-left: 10px;"/>
                    <img src="~/Content/Img/12.png"style="width:30px;" />
                    <img src="~/Content/Img/13.png"style="width:30px;" />
                    <img src="~/Content/Img/4.png" style="width:30px;"/>
                    <img src="~/Content/Img/5.png"style="width:30px;" />
                    <img src="~/Content/Img/6.png"style="width:30px;" />
                    <img src="~/Content/Img/7.png"style="width:30px;" />
                    <img src="~/Content/Img/8.png"style="width: 35px; " />
                    <img src="~/Content/Img/9.png" style="width: 35px; "/>
                    <img src="~/Content/Img/10.png"style="width:50px; margin-top:5px;"/>
                </div>

            </div>
        </div>
    </div>
</div>

CapstoneProject_Ecommerce/Views/Home/Contatti.cshtml
@model CapstoneProject_Ecommerce.Models.Email

@{
    ViewBag.Title = "Contatti";
}

<h2>Contatti</h2>
<div class="container" id="ContEdit">

    <div>
        @Html.ActionLink("HOME", "Index", "PRODOTTO")
    </div>
    <hr />

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal ContEditBox2 p-2 flex-column">

            @Html.ValidationSummary(true, "", new { @class = "text-danger" })


            <div class="form-group">
                @Html.LabelFor(model => model.mittenteEmail, htmlAttributes: new { @class = "control-label" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.mittenteEmail, new { htmlAttributes = new { @class = "form-control", @style = " width:100%" } })
                    @Html.ValidationMessageFor(model => model.mittenteEmail, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Oggetto, htmlAttributes: new { @class = "control-label" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Oggetto, new { htmlAttributes = new { @class = "form-control", @style = " width:100%" } })
                    @Html.ValidationMessageFor(model => model.Oggetto, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Messaggio, htmlAttributes: new { @class = "control-label" })
                <div class="col-md-10">
                    @Html.TextAreaFor(model => model.Messaggio, new { htmlAttributes = new { @class = "form-control", @style = " width:100%" } })
                    @Html.ValidationMessageFor(model => model.Messaggio, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10 text-center mt-5" id="contBtn" style="width: 100%">
                <input type="submit" value="INVIA" class="btn btn-default" />
            </div>
        </div>
    }
    @if (Model != null && !string.IsNullOrEmpty(Model.mittenteEmail))
    {
        <div>L'indirizzo email del mittente è: @Model.mittenteEmail</div>
    }
</div>

    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }

CapstoneProject_Ecommerce/Views/Home/EmailDone.cshtml
@model CapstoneProject_Ecommerce.Models.USER

@{
    ViewBag.Title = "EmailDone";
}

<h2>Contatti</h2>
<div class="container" id="ContEdit">

    <div>
        @Html.ActionLink("HOME", "Index", "PRODOTTO")
    </div>
    <hr />

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal ContEditBox2 p-2 flex-column">
             
            <h2 style="color:green"> Email inviata con successo!</h2>
            
        </div>
    }
</div>

CapstoneProject_Ecommerce/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}


   

        <div id="carouselExampleInterval" class="carousel slide" data-bs-ride="carousel">
            <div class="carousel-inner d-flex">
                <div class="carousel-item active" data-bs-interval="2000">                   
                    <video controls autoplay muted>
                        <source src="~/Content/Img/SHOPbunn.mp4" type="video/mp4" class="d-block w-100" />
                    </video>
                </div>
                <div class="carousel-item" data-bs-interval="3000">
                    <video controls autoplay muted>
                        <source src="~/Content/Img/SHOP0.mp4" type="video/mp4" class="d-block w-100" />
                    </video>
                </div>
                <div class="carousel-item" data-bs-interval="3000">
                    <video controls autoplay muted>
                        <source src="~/Content/Img/SHOP7.mp4" type="video/mp4" class="d-block w-100" />
                    </video>
                </div>
            </div>
            <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleInterval" data-bs-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Previous</span>
            </button>
            <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleInterval" data-bs-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Next</span>
            </button>
        </div>
     

CapstoneProject_Ecommerce/Views/Home/Login.cshtml
@model CapstoneProject_Ecommerce.Models.USER

@{
    ViewBag.Title = "Login";
}

@*<h2>AREA RISERVATA</h2>*@

<div class="container" >

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="blurred-box ContLoginP">
        <div class="form-horizontal ContLogin">

            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group p-2 mx-5">
                @Html.LabelFor(model => model.Username, htmlAttributes: new { @class = "control-label col-md-2 userName text-center" })
                <div>
                    @Html.EditorFor(model => model.Username, new { htmlAttributes = new { @class = "form-control", @style=" width:100%" } })
                    @Html.ValidationMessageFor(model => model.Username, "", new { @class = "text-danger" })
                </div>
            </div>


            <div class="form-group p-2 mx-5">
                @Html.LabelFor(model => model.Pass, htmlAttributes: new { @class = "control-label passWord text-center" })
                <div>
                    @Html.EditorFor(model => model.Pass, new { htmlAttributes = new { @class = "form-control", @Type = "password", @style = " width:100%" } })
                    @Html.ValidationMessageFor(model => model.Pass, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="mb-2 mx-5" style="width:165px" >
                @Html.ActionLink("Registrati", "Register")
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10 text-center" id="contBtn" style="width: 100%" >
                    <input type="submit" value="Accedi" class="btn btn-default" />
                </div>
            </div>
        </div>
    </div>
}
 </div>   

    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }

CapstoneProject_Ecommerce/Views/Home/Register.cshtml
@model CapstoneProject_Ecommerce.Models.USER

@{
    ViewBag.Title = "Register";
}

@*<h2>Register</h2>*@


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class=" ContLoginP">

        <div class="form-horizontal ContLogin">

            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group p-2 mx-5">
                @Html.LabelFor(model => model.Username, htmlAttributes: new { @class = "control-label  userName text-center" })
                <div>
                    @Html.EditorFor(model => model.Username, new { htmlAttributes = new { @class = "form-control", @style = " width:100%" } })
                    @Html.ValidationMessageFor(model => model.Username, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group p-2 mx-5">
                @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label userName text-center" })
                <div>
                    @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control", @style = " width:100%" } })
                    @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group p-2 mx-5">
                @Html.LabelFor(model => model.Cognome, htmlAttributes: new { @class = "control-label  userName text-center" })
                <div>
                    @Html.EditorFor(model => model.Cognome, new { htmlAttributes = new { @class = "form-control", @style = " width:100%" } })
                    @Html.ValidationMessageFor(model => model.Cognome, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group p-2 mx-5">
                @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label  userName text-center" })
                <div>
                    @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control", @style = " width:100%" } })
                    @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group p-2 mx-5">
                @Html.LabelFor(model => model.Pass, htmlAttributes: new { @class = "control-label userName text-center" })
                <div>
                    @Html.EditorFor(model => model.Pass, new { htmlAttributes = new { @class = "form-control", @style = " width:100%" } })
                    @Html.ValidationMessageFor(model => model.Pass, "", new { @class = "text-danger" })
                </div>
            </div>


            <div class="mx-5 mb-2">
                @Html.ActionLink("Torna a login", "Login", "Home")
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10 text-center" id="contBtn" style="width: 100%">
                    <input type="submit" value="Registrati" class="btn btn-default" />
                </div>
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}